spring.application.name=revive_app

spring.cloud.vault.uri=http://localhost:8300
spring.cloud.vault.kv.default-context=revive_app
spring.cloud.vault.token=root
spring.cloud.vault.scheme=http
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.config.import:  vault://

logging.level.org.hibernate=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG

# KV engine configuration
# spring.cloud.vault.kv.enabled=true
# spring.cloud.vault.kv.backend=secret
# spring.cloud.vault.kv.default-context=revive_app
# spring.cloud.vault.kv.application-name=revive_app
# spring.config.import:  vault://

# spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Revive;encrypt=true;trustServerCertificate=true
# spring.datasource.username=v.marcos
# spring.datasource.password=Y4F6kZiDa@f&!C
# spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# spring.datasource.connection-timeout=30000

# JPA/Hibernate configuration
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
