spring.application.name=revive_app

spring.cloud.vault.uri=http://localhost:8300
spring.cloud.vault.kv.default-context=revive_app
spring.cloud.vault.token=root
spring.cloud.vault.scheme=http
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.config.import:  vault://

logging.level.org.hibernate=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
